#!/bin/bash

function send_log(){
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIFICATIONS MULTI LOGIN ⚠️</b>
<code>────────────────────</code>
<code>Username  : </code><code>$user</code>
<code>Online IP : </code><code>$cekcek</code>
<code>Limit Ip  : </code><code>$iplimit</code>
<code>────────────────────</code>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function ssh_mulog(){
usernamessh=$(echo "$cekcek1" | awk '{print $5}');
date1=$(echo "$cekcek1" | awk '{print $1}');
time1=$(echo "$cekcek1" | awk '{print $2, $3}');
jum=$(echo "$cekcek1" | awk '{print $7}');

CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIF MULTI LOGIN SSH ⚠️</b>
<code>────────────────────</code>
<code>Username     : </code><code>$usernamessh</code>
<code>Tanggal      : </code><code>$date1</code>
<code>Waktu Login  : </code><code>$time1</code>
<code>Max Device   : </code><code>$iplimit</code>
<code>Total Device : </code><code>$jum Device</code>
<code>────────────────────</code>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}

function vmip(){
#LIMITVMESSIP
echo -n > /var/log/xray/access.log
sleep 440
data=( `ls /etc/kyt/limit/vmess/ip`);
    for user in "${data[@]}"
    do
        iplimit=$(cat /etc/kyt/limit/vmess/ip/$user)
        ehh=$(cat /var/log/xray/access.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq);
        cekcek=$(echo -e "$ehh" | wc -l);
        if [[ $cekcek -gt $iplimit ]]; then
            exp=$(grep -w "^### $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
                  sed -i "/^### $user $exp/,/^},{/d" /etc/xray/config.json
                  sed -i "/^### $user $exp/d" /etc/vmess/.vmess.db
                  systemctl restart xray >> /dev/null 2>&1
                  jum2=$(cat /tmp/ipvmess.txt | wc -l)
                    rm -rf /etc/vmess/$user
                    rm -rf /etc/kyt/limit/vmess/ip/$user
                    rm -rf /etc/limit/vmess/$user
                    rm -rf /var/www/html/vmess-$user.txt
                  send_log
                else
            echo ""
        fi
        sleep 0.1
    done
}
function vlip(){
#LIMITVLESSIP
echo -n > /var/log/xray/access.log
sleep 440
data=( `ls /etc/kyt/limit/vless/ip`);
    for user in "${data[@]}"
    do
        iplimit=$(cat /etc/kyt/limit/vless/ip/$user)
        ehh=$(cat /var/log/xray/access.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq);
        cekcek=$(echo -e "$ehh" | wc -l);
        if [[ $cekcek -gt $iplimit ]]; then
            exp=$(grep -w "^#& $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
                  sed -i "/^#& $user $exp/,/^},{/d" /etc/xray/config.json
                  sed -i "/^### $user $exp/d" /etc/vless/.vless.db
                  systemctl restart xray >> /dev/null 2>&1
                  jum2=$(cat /tmp/ipvless.txt | wc -l)
                    rm -rf /etc/kyt/limit/vless/ip/$user
                    rm -rf /etc/vless/$user
                    rm -rf /etc/kyt/limit/vless/ip/$user
                    rm -rf /etc/limit/vless/$user
                    rm -rf /var/www/html/vless-$user.txt
                  send_log
                else
            echo ""
        fi
        sleep 0.1
    done
}
function trip(){
#LIMITIPTROJAN
echo -n > /var/log/xray/access.log
sleep 440
data=( `ls /etc/kyt/limit/trojan/ip`);
    for user in "${data[@]}"
    do
        iplimit=$(cat /etc/kyt/limit/trojan/ip/$user)
        ehh=$(cat /var/log/xray/access.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq);
        cekcek=$(echo -e "$ehh" | wc -l);
        if [[ $cekcek -gt $iplimit ]]; then
            exp=$(grep -w "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
                  sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
                  sed -i "/^### $user $exp/d" /etc/trojan/.trojan.db
                  systemctl restart xray >> /dev/null 2>&1
                  jum2=$(cat /tmp/iptrojan.txt | wc -l)
                    rm -rf /etc/trojan/$user
                    rm -rf /etc/kyt/limit/trojan/ip/$user
                    rm -rf /etc/limit/trojan/$user
                    rm -rf /var/www/html/trojan-$user.txt
                  send_log
                else
            echo ""
        fi
        sleep 0.1
    done
}

##Limit SS
function ssws(){
echo -n > /var/log/xray/access.log
sleep 440
data=( `ls /etc/kyt/limit/shadowsocks/ip`);
    for user in "${data[@]}"
    do
        iplimit=$(cat /etc/kyt/limit/shadowsocks/ip/$user)
        ehh=$(cat /var/log/xray/access.log | grep "$user" | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq);
        cekcek=$(echo -e "$ehh" | wc -l);
        if [[ $cekcek -gt $iplimit ]]; then
            exp=$(grep -w "^#!# $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
                  sed -i "/^#!# $user $exp/,/^},{/d" /etc/xray/config.json
                  sed -i "/^### $user $exp/d" /etc/shadowsocks/.shadowsocks.db
                  systemctl restart xray >> /dev/null 2>&1
                  jum2=$(cat /tmp/ipshadowsocks.txt | wc -l)
                    rm -rf /etc/shadowsocks/$user
                    rm -rf /etc/kyt/limit/shadowsocks/ip/$user
                    rm -rf /etc/limit/shadowsocks/$user
                    rm -rf /var/www/html/shadowsocks-$user.txt
                  send_log
                else
            echo ""
        fi
        sleep 0.1
    done
}

function sship(){
sleep 440
waktu=$(date)
mulog=$(member_mulog)
data=( $(ls /etc/kyt/limit/ssh/ip) )
    for user in "${data[@]}"
    do
        cekcek=$(echo "$mulog" | grep $user | awk '{print $7}' | uniq)
        getpid=$(echo "$mulog" | grep $user)
        kill=$(echo "$getpid" | awk -F' - ' '{print $NF}')
        pid_array=($kill)
        iplimit=$(cat /etc/kyt/limit/ssh/ip/$user)
        cekcek1=$(echo -e "$mulog" | grep $user);
        if [[ $cekcek -gt $iplimit ]]; then
        userdel -f -r $user
        echo -e "$waktu Alasan: Multilogin\nRemoved User: $user Login: $mulog IP Max: $iplimit IP \n" >> /etc/kyt/log/ssh.log
        rm -rf /var/www/html/ssh-$user.txt
        rm -f /etc/kyt/limit/ssh/ip/$user
        ssh_mulog
        for pid in "${pid_array[@]}"; do
            if [[ -n $pid ]]; then 
                kill $pid; 
            fi
        done
        service ssh restart
        service dropbear restart
        else
        echo > /dev/null
        fi
        sleep 0.1
    done
}

if [[ ${1} == "vmip" ]]; then
vmip
elif [[ ${1} == "vlip" ]]; then
vlip
elif [[ ${1} == "trip" ]]; then
trip
elif [[ ${1} == "ssws" ]]; then
ssws
elif [[ ${1} == "sship" ]]; then
sship
fi




